[project]
name = "asthma-risk-system"
version = "0.1.0"
requires-python = ">=3.10, <3.11"

[tool.poetry]
# optional if using poetry

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
