[project]
name = "asthma-risk-api"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
    "Flask",
    "gunicorn",
    "numpy",
    "tflite-runtime",
    "librosa",
    "werkzeug"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"